# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.show_sql=true
# spring.jpa.properties.hibernate.format_sql=true

# Nota: Eles fucionam com a forma hierarquia
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
